name: app
description: Flutter Architecture Blueprints project.
version: 1.0.0+1

publish_to: 'none'

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Common
  intl:
  path_provider: ^2.0.14


  # Collection
  collection: ^1.17.0

  # Convert between Enum and String
  enum_to_string: ^2.0.1

  # RiverPod
  flutter_hooks: ^0.18.6
  hooks_riverpod: ^2.3.5
  riverpod_annotation: ^2.1.0

  # API
  dio: ^5.1.1
  pretty_dio_logger: ^1.3.1
  retrofit: ^4.0.1
  ua_client_hints: ^1.1.3

  # Database
  shared_preferences: ^2.1.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1

  # Firebase
  firebase_core: ^2.10.0
  firebase_messaging: ^14.4.1
  firebase_crashlytics: ^3.2.0
  firebase_performance_dio: ^0.5.0
  firebase_remote_config: ^4.1.0
  flutter_local_notifications: ^14.0.0+1

  # Model
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  equatable: ^2.0.5



  # For UI
  cupertino_icons: ^1.0.5
  flutter_rating_bar: ^4.0.1
  google_fonts: ^4.0.3
  webview_flutter: ^3.0.0

  # Screen Route
  auto_route: ^6.3.0

  # Image
  cached_network_image: ^3.2.3
  flutter_svg: ^2.0.5

  # Scroll
  sliding_up_panel: ^2.0.0+1
  carousel_slider: ^4.1.1

  # Loading
  progress_indicators: ^1.0.0
  loading_indicator: ^3.1.0

  # For querying information about an application package.
  package_info_plus: ^3.1.2

  # For launching url
  url_launcher: ^6.1.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  build_runner: ^2.3.3

  # model gen
  json_serializable: ^6.6.1

  # Database
  isar_generator: ^3.1.0+1

  # UI gen
  auto_route_generator: ^6.2.0

  # Assets gen
  flutter_gen_runner: ^5.3.0

  # API gen
  retrofit_generator: ^6.0.0+2

  # Riverpod gen
  riverpod_generator: ^2.2.0

  # For change package name quickly
  change_app_package_name: ^1.1.0

flutter_gen:
  output: lib/gen/
  line_length: 120
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/svgs/

  fonts:
    - family: Rotunda
      fonts:
        - asset: assets/fonts/Rotunda-Bold.otf
          weight: 700
