name: app
description: Flutter Architecture Blueprints project.
version: 1.0.0+1

publish_to: 'none'

environment:
  sdk: '>=2.13.0 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # For Google and Firebase
  firebase_core: ^2.5.0
  firebase_auth: ^4.2.6
  firebase_crashlytics: ^3.0.12
  firebase_performance: ^0.9.0+13
  firebase_remote_config: ^3.0.10

  # For Firebase Cloud Messaging
  firebase_messaging: ^14.2.2
  flutter_local_notifications: ^13.0.0

  # For Architecture
  flutter_hooks: ^0.18.5+1
  hooks_riverpod: ^2.2.0

  # For Networking
  dio: ^5.0.0
  retrofit: ^4.0.1
  # For User-Agent Client Hints
  ua_client_hints: ^1.1.3

  # For Model
  json_serializable: ^6.1.3
  freezed_annotation: ^2.2.0

  # For save data local
  shared_preferences: ^2.0.17

  # For DateTime
  intl: ^0.17.0

  # Convert between Enum and String
  enum_to_string: ^2.0.1

  # For route
  auto_route: ^5.0.4

  # For UIs
  cupertino_icons: ^1.0.5
  google_fonts: ^4.0.3
  flutter_svg: ^1.1.6
  webview_flutter: ^3.0.0

  # For querying information about an application package.
  package_info_plus: ^3.0.3

  # For launching url
  url_launcher: ^6.1.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.3

  # For Networking
  retrofit_generator: ^5.0.0

  # For Assets
  flutter_gen_runner: ^4.3.0

  # For Model
  freezed: ^2.1.0

  # For Analyzer
  flutter_lints: ^2.0.1

  # For AutoRoute
  auto_route_generator: ^5.0.2

  # For change package name quickly
  change_app_package_name: ^1.1.0

flutter_gen:
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/svgs/

  fonts:
    - family: Rotunda
      fonts:
        - asset: assets/fonts/Rotunda-Bold.otf
          weight: 700
